export const REGISTER = 'REGISTER'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN = 'LOGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const RESET_PASSWORD = 'RESET PASSWORD'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const USER_EMAIL = 'USER_EMAIL'
export const USER_EMAIL_SUCCESS = 'USER_EMAIL_SUCCESS'
export const USER_EMAIL_ERROR = 'USER_EMAIL_ERROR'

export const LOGIN_USER_DETAILS = 'LOGIN_USER_DETAILS'

export const FETCH_CATEGORY = 'FETCH_CATEGORY'

export const FETCH_PLACE = 'FETCH_PLACE'

export const RECOMMENDED_PLACE = 'RECOMMENDED_PLACE'

export const GET_PLACE = 'GET_PLACE'
export const GET_PLACE_SUCCESS = 'GET_PLACE_SUCCESS'
export const GET_PLACE_FAIL = 'GET_PLACE_FAIL'

export const GET_PLACE_BY_CATEGORY = 'GET_PLACE_BY_CATEGORY'
export const GET_PLACE_BY_CATEGORY_SUCCESS = 'GET_PLACE_BY_CATEGORY_SUCCESS'
export const GET_PLACE_BY_CATEGORY_FAIL = 'GET_PLACE_BY_CATEGORY_FAIL'

export const REVIEW = 'REVIEW'
export const REVIEW_SUCCESS = 'REVIEW_SUCCESS'
export const REVIEW_FAIL = 'REVIEW_FAIL'

export const CURRENT_LOCATION = 'CURRENT_LOCATION'

export const LOGOUT_USER = 'LOGOUT_USER'

export const PICTURE_UPLOAD = 'PICTURE_UPLOAD'
export const PICTURE_UPLOAD_SUCCESS = 'PICTURE_UPLOAD_SUCCESS'
export const PICTURE_UPLOAD_FAIL = 'PICTURE_UPLOAD_FAIL'
export const PICUTRE_UPDATE_SUCCESS = 'PICUTRE_UPDATE_SUCCESS'
export const PICTURE_UPDATE_FAIL = 'PICTURE_UPDATE_FAIL'